language: go
go:
  - 1.14
before_install:
  - sudo apt-get -y install clickhouse-server clickhouse-client
services:
  - clickhouse
env:
  GO111MODULE=on
  DBATCHER_TEST_CLICKHOUSE_DSN_KEY="tcp://127.0.0.1:9000?user=default"
script:
  - go mod download
  - go test ./... -v -race -covermode=atomic -coverprofile="coverage.out"

after_success:
  - bash <(curl -s https://codecov.io/bash)
