language: go
go:
  - 1.14

env:
  GO111MODULE=on

script:
  - go mod download
  - go test ./... -v -race -covermode=atomic -coverprofile="coverage.out"

after_success:
  - bash <(curl -s https://codecov.io/bash)
