language: go
go:
  - 1.14
before_install:
  - sudo apt-get install apt-transport-https ca-certificates dirmngr
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv E0C56BD4

  - echo "deb https://repo.clickhouse.com/deb/stable/ main/" | sudo tee /etc/apt/sources.list.d/clickhouse.list
  - sudo apt-get update

  - sudo apt-get install -y clickhouse-server clickhouse-client

  - sudo service clickhouse-server start
services:
  - clickhouse
env:
  GO111MODULE=on
  DBATCHER_TEST_CLICKHOUSE_DSN_KEY="tcp://127.0.0.1:9000?user=default"
script:
  - go mod download
  - go test ./... -v -race -covermode=atomic -coverprofile="coverage.out"

after_success:
  - bash <(curl -s https://codecov.io/bash)
